version: 2
registries:
  github-pkg:
    type: "npm-registry"
    url: "https://npm.pkg.github.com"
    token: "${{secrets.NODE_AUTH_TOKEN}}"
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
      time: "09:22"
      timezone: "Asia/Kolkata"
    groups:
      staystack:
        patterns:
          - "*staystack*"
          - "@staytuned*/*"
      development-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      security-patches:
        applies-to: "security-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    cooldown:
      default-days: 0
      semver-major-days: 0
      semver-minor-days: 0
      semver-patch-days: 0
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 5
